# Generated by Django 5.2.11 on 2026-06-10 13:55

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha del Feriado')),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo (ej: Día del Trabajador)')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('año_dictado', models.IntegerField(verbose_name='Año en que se dicta (1, 2, 3...)')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDeEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Plan')),
                ('resolucion_ministerial', models.CharField(max_length=50, verbose_name='Resolución')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido/s')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('tutor_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tutor Principal')),
                ('tutor_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tutor Alternativo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doc_dni', models.BooleanField(default=False, verbose_name='Fotocopia DNI')),
                ('doc_vacunas', models.BooleanField(default=False, verbose_name='Certificado de Vacunas')),
                ('doc_partida', models.BooleanField(default=False, verbose_name='Partida de Nacimiento')),
                ('doc_primaria', models.BooleanField(default=False, verbose_name='Título Secundario')),
                ('doc_pase', models.BooleanField(default=False, verbose_name='Pase de Escuela Anterior')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_alumno', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido/s')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_docente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_lectivo', models.IntegerField(default=2026, verbose_name='Ciclo Lectivo (Año)')),
                ('cuatrimestre', models.CharField(choices=[('1C', '1er Cuatrimestre'), ('2C', '2do Cuatrimestre'), ('AN', 'Anual')], max_length=2, verbose_name='Cuatrimestre')),
                ('dias_horarios', models.CharField(help_text='Ej: Lunes y Miércoles 19:00 a 21:00', max_length=200, verbose_name='Días y Horarios')),
                ('tipo_aprobacion', models.CharField(choices=[('PROM', 'Promocionable'), ('FIN', 'Final Obligatorio')], default='FIN', max_length=4, verbose_name='Tipo de Aprobación')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones_asignadas', to='gestion.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='gestion.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('REG', 'Cursando (Regular)'), ('LIB', 'Quedó Libre'), ('APR', 'Cursada Aprobada'), ('PROM', 'Materia Promocionada')], default='REG', max_length=4, verbose_name='Estado')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='gestion.alumno')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_inscriptos', to='gestion.comision')),
            ],
            options={
                'unique_together': {('alumno', 'comision')},
            },
        ),
        migrations.CreateModel(
            name='Correlatividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CUR', 'Cursada Regular'), ('APR', 'Final Aprobado')], max_length=3, verbose_name='Tipo de Requisito')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlativas_requeridas', to='gestion.materia')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_requisito_de', to='gestion.materia')),
            ],
        ),
        migrations.CreateModel(
            name='MesaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('tribunal', models.CharField(help_text='Nombres de los profesores', max_length=255, verbose_name='Tribunal Docente')),
                ('ciclo_lectivo', models.IntegerField(default=2026, verbose_name='Ciclo Lectivo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_examen', to='gestion.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('instancia', models.CharField(max_length=50, verbose_name='Instancia (Ej: 1er Parcial, TP1)')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='gestion.inscripcion')),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='gestion.plandeestudio'),
        ),
        migrations.CreateModel(
            name='PlanillaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planillas_asistencia', to='gestion.comision')),
            ],
            options={
                'unique_together': {('comision', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Llegada Tarde (Media Falta)'), ('J', 'Falta Justificada')], default='P', max_length=1, verbose_name='Estado')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='gestion.alumno')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='gestion.planilladiaria')),
            ],
        ),
        migrations.CreateModel(
            name='TicketReclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Reclamo/Consulta')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('PROCESO', 'En Proceso'), ('RESUELTO', 'Resuelto')], default='ABIERTO', max_length=10, verbose_name='Estado')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='gestion.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Final')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('APR', 'Aprobado'), ('REP', 'Reprobado'), ('AUS', 'Ausente')], default='PEND', max_length=4, verbose_name='Estado')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_inscriptas', to='gestion.alumno')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptos', to='gestion.mesaexamen')),
            ],
            options={
                'unique_together': {('alumno', 'mesa')},
            },
        ),
    ]
