# Generated by Django 5.2.11 on 2026-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='tutor_1',
        ),
        migrations.RemoveField(
            model_name='alumno',
            name='tutor_2',
        ),
        migrations.AddField(
            model_name='alumno',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Fijo'),
        ),
    ]
