# Generated by Django 5.2.11 on 2026-06-10 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_alumno_tutor_1_remove_alumno_tutor_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='dias_horarios',
        ),
        migrations.CreateModel(
            name='HorarioComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado')], max_length=1)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='gestion.comision')),
            ],
        ),
    ]
