# Generated by Django 5.2.11 on 2026-06-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_comision_dias_horarios_horariocomision'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='modalidad',
            field=models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual'), ('B', 'Bimodal (1 sem presencial / 1 sem virtual)')], default='P', max_length=1, verbose_name='Modalidad'),
        ),
    ]
