# Generated by Django 5.2.11 on 2026-06-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_comision_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AddField(
            model_name='comision',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='comision',
            name='semana_inicio_bimodal',
            field=models.CharField(blank=True, choices=[('P', 'Arranca Presencial'), ('V', 'Arranca Virtual')], max_length=1, null=True, verbose_name='Semana de Inicio (Bimodal)'),
        ),
    ]
