# Generated by Django 5.2.11 on 2026-06-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_comision_fecha_fin_comision_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='cerrada',
            field=models.BooleanField(default=False, verbose_name='Comisión Cerrada'),
        ),
        migrations.AddField(
            model_name='comision',
            name='inscripciones_abiertas',
            field=models.BooleanField(default=True, verbose_name='Inscripciones Abiertas'),
        ),
    ]
