# Generated by Django 5.2.11 on 2026-06-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_comision_cerrada_comision_inscripciones_abiertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaexamen',
            name='cerrada',
            field=models.BooleanField(default=False, verbose_name='Mesa Cerrada'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='libro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Libro'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='turno',
            field=models.CharField(choices=[('FEB_MAR', 'Febrero / Marzo'), ('JUL_AGO', 'Julio / Agosto'), ('NOV_DIC', 'Noviembre / Diciembre'), ('ESPECIAL', 'Mesa Especial / Única')], default='NOV_DIC', max_length=20, verbose_name='Turno'),
        ),
    ]
