# Generated by Django 5.2.11 on 2026-06-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_mesaexamen_cerrada_mesaexamen_folio_mesaexamen_libro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='gestion.plandeestudio', verbose_name='Plan de Estudios'),
        ),
    ]
