# Generated by Django 5.2.11 on 2026-06-10 18:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alumno_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolucion', models.CharField(max_length=100, verbose_name='Número de Resolución')),
                ('institucion_origen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institución de Origen')),
                ('fecha_otorgamiento', models.DateField(default=datetime.date.today, verbose_name='Fecha de Otorgamiento')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Reconocida')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias', to='gestion.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_otorgadas', to='gestion.materia')),
            ],
            options={
                'unique_together': {('alumno', 'materia')},
            },
        ),
    ]
