# Generated by Django 5.2.11 on 2026-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_equivalencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado_alumno',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo / Abandonó'), ('EGR', 'Egresado'), ('COND_DOC', 'Condicionado (Documentación)'), ('COND_PAG', 'Condicionado (Falta de Pago)')], default='ACT', max_length=10, verbose_name='Estado'),
        ),
    ]
