# Generated by Django 5.2.11 on 2026-06-12 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alumno_codigo_postal_alumno_comuna_zona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Carga'),
        ),
    ]
