# Generated by Django 5.2.11 on 2026-06-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_nota_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaexamen',
            name='tribunal',
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='presidente_mesa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_presidente', to='gestion.docente'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='vocal_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_vocal1', to='gestion.docente'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='vocal_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_vocal2', to='gestion.docente'),
        ),
    ]
