# Generated by Django 5.2.11 on 2026-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_remove_mesaexamen_tribunal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='cuatrimestre_dictado',
            field=models.CharField(choices=[('1C', '1er Cuatrimestre'), ('2C', '2do Cuatrimestre'), ('AN', 'Anual')], default='1C', max_length=2),
        ),
    ]
