# Generated by Django 5.2.11 on 2026-06-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_materia_cuatrimestre_dictado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('tipo', models.CharField(choices=[('FERIADO', 'Feriado Nacional / Provincial'), ('EVENTO', 'Evento Institucional'), ('EXAMEN', 'Semana de Exámenes')], default='EVENTO', max_length=10, verbose_name='Tipo de Evento')),
                ('todo_el_dia', models.BooleanField(default=True, verbose_name='Todo el día')),
            ],
        ),
    ]
