# Generated by Django 5.2.11 on 2026-06-13 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_eventoinstitucional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('tipo_destinatario', models.CharField(choices=[('TODOS', 'Toda la Institución'), ('DOCENTES', 'Todos los Docentes'), ('DOCENTES_CARRERA', 'Docentes por Carrera'), ('ALUMNOS', 'Todos los Alumnos'), ('ALUMNOS_CARRERA', 'Alumnos por Carrera'), ('COMISION', 'Alumnos de una Comisión Específica')], max_length=20, verbose_name='Destinatarios')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicados_enviados', to=settings.AUTH_USER_MODEL)),
                ('comision', models.ForeignKey(blank=True, help_text='Requerido si se envía a una comisión', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.comision')),
                ('plan_estudio', models.ForeignKey(blank=True, help_text='Requerido si se envía por carrera', null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.plandeestudio')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_individuales', to='gestion.comunicado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'comunicado')},
            },
        ),
    ]
