# Generated by Django 5.2.11 on 2026-06-15 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_docente_celular_docente_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comision',
            name='docente_auxiliar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comisiones_auxiliares', to='gestion.docente', verbose_name='Pareja Pedagógica'),
        ),
    ]
