# Generated by Django 5.2.11 on 2026-06-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_comision_docente_auxiliar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaexamen',
            name='inscripciones_abiertas',
            field=models.BooleanField(default=True, verbose_name='Inscripciones Abiertas'),
        ),
    ]
