# Generated by Django 5.2.11 on 2026-06-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_mesaexamen_inscripciones_abiertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificativoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ausencia', models.DateField(verbose_name='Fecha de Inasistencia')),
                ('archivo', models.FileField(upload_to='justificativos/', verbose_name='Certificado Médico/Laboral')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente de Revisión'), ('APR', 'Aprobado'), ('RECH', 'Rechazado')], default='PEND', max_length=4, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones (Bedelía)')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativos', to='gestion.alumno')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativos', to='gestion.comision')),
            ],
        ),
    ]
