# Generated by Django 5.2.11 on 2026-06-20 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_justificativoasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladiaria',
            name='tema_dictado',
            field=models.TextField(blank=True, null=True, verbose_name='Tema de la Clase (Libro de Temas)'),
        ),
        migrations.CreateModel(
            name='ProgramaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='programas/', verbose_name='Archivo del Programa')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('comision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programa', to='gestion.comision')),
            ],
        ),
    ]
