# Generated by Django 5.2.11 on 2026-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_planilladiaria_tema_dictado_programacomision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado_alumno',
            field=models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo / Abandonó'), ('EGR', 'Egresado'), ('COND_DOC', 'Condicionado (Documentación)'), ('COND_PAG', 'Condicionado (Falta de Pago)'), ('ASP', 'Aspirante (Pre-Inscripto)')], default='ACT', max_length=10, verbose_name='Estado'),
        ),
    ]
