# Generated by Django 5.2.11 on 2026-08-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_alter_alumno_estado_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='carreras_coordinadas',
            field=models.ManyToManyField(blank=True, related_name='coordinadores', to='gestion.plandeestudio', verbose_name='Carreras que Coordina'),
        ),
    ]
