# Generated by Django 5.2.11 on 2026-08-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0023_docente_carreras_coordinadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='instancia',
            field=models.CharField(choices=[('1er Parcial', '1er Parcial'), ('2do Parcial', '2do Parcial'), ('3er Parcial', '3er Parcial'), ('4to Parcial', '4to Parcial'), ('5to Parcial', '5to Parcial'), ('6to Parcial', '6to Parcial'), ('7mo Parcial', '7mo Parcial'), ('8vo Parcial', '8vo Parcial'), ('Recuperatorio', 'Recuperatorio'), ('Trabajo Práctico', 'Trabajo Práctico'), ('Concepto', 'Concepto'), ('Nota Final', 'Nota Final')], max_length=50, verbose_name='Instancia (Ej: 1er Parcial, TP1)'),
        ),
    ]
