# Generated by Django 5.2.11 on 2026-08-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0024_alter_nota_instancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='chances_restantes',
            field=models.IntegerField(default=10, verbose_name='Chances Restantes'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='vencimiento_cursada',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento de Cursada'),
        ),
    ]
