# Generated by Django 5.2.11 on 2026-08-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_inscripcion_chances_restantes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='tipo_aprobacion',
            field=models.CharField(choices=[('PROM', 'Promocionable'), ('FIN', 'Final Obligatorio')], default='FIN', max_length=4, verbose_name='Tipo de Aprobación por Defecto'),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='tipo_destinatario',
            field=models.CharField(choices=[('TODOS', 'Toda la Institución'), ('DOCENTES', 'Todos los Docentes'), ('DOCENTES_CARRERA', 'Docentes por Carrera'), ('ALUMNOS', 'Todos los Alumnos'), ('ALUMNOS_CARRERA', 'Alumnos por Carrera'), ('COMISION', 'Alumnos de una Comisión Específica'), ('ADMINS', 'Solo Administradores (Sistema)')], max_length=20, verbose_name='Destinatarios'),
        ),
    ]
