# Generated by Django 5.2.11 on 2026-08-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0026_materia_tipo_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Institucional'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico Personal'),
        ),
    ]
