# Generated by Django 5.2.11 on 2026-08-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0027_alumno_correo_institucional_alter_alumno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='valor_nota',
            field=models.IntegerField(verbose_name='Nota'),
        ),
    ]
