# Generated by Django 5.2.11 on 2026-08-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0029_alter_nota_instancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalencia',
            name='nota',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota Reconocida'),
        ),
        migrations.AlterField(
            model_name='inscripcionmesa',
            name='nota_final',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nota Final'),
        ),
    ]
