# Generated by Django 5.2.11 on 2026-09-14 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0030_alter_equivalencia_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='gestion.plandeestudio', verbose_name='Plan de Estudios (Obs)'),
        ),
        migrations.CreateModel(
            name='InscripcionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('estado', models.CharField(choices=[('CURSANDO', 'Cursando'), ('EGRESADO', 'Egresado'), ('ABANDONADA', 'Abandonada')], default='CURSANDO', max_length=15, verbose_name='Estado en la Carrera')),
                ('legajo_numero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Legajo')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_carreras', to='gestion.alumno')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_alumnos', to='gestion.plandeestudio')),
            ],
            options={
                'unique_together': {('alumno', 'plan')},
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='alumnos_inscriptos', through='gestion.InscripcionCarrera', to='gestion.plandeestudio'),
        ),
    ]
