# Generated by Django 5.2.11 on 2026-09-14 21:27

from django.db import migrations

def copy_plan_to_carreras(apps, schema_editor):
    Alumno = apps.get_model('gestion', 'Alumno')
    InscripcionCarrera = apps.get_model('gestion', 'InscripcionCarrera')
    
    for alumno in Alumno.objects.filter(plan__isnull=False):
        # We check if student is graduated
        estado = 'CURSANDO'
        if alumno.estado_alumno == 'EGR':
            estado = 'EGRESADO'
        elif alumno.estado_alumno == 'INA':
            estado = 'ABANDONADA'
            
        InscripcionCarrera.objects.create(
            alumno=alumno,
            plan=alumno.plan,
            estado=estado
        )

def reverse_copy(apps, schema_editor):
    InscripcionCarrera = apps.get_model('gestion', 'InscripcionCarrera')
    InscripcionCarrera.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0031_alter_alumno_plan_inscripcioncarrera_alumno_carreras'),
    ]

    operations = [
        migrations.RunPython(copy_plan_to_carreras, reverse_copy),
    ]
