# Generated by Django 5.2.11 on 2026-09-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0032_migrate_plan_to_carreras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='plan',
        ),
    ]
