# Generated by Django 5.2.11 on 2026-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0033_remove_alumno_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='estado',
            field=models.CharField(choices=[('PREINSCRIPTO', 'Pre-inscripto (Aspirante)'), ('CURSANDO', 'Cursando'), ('EGRESADO', 'Egresado'), ('ABANDONADA', 'Abandonada')], default='CURSANDO', max_length=15, verbose_name='Estado en la Carrera'),
        ),
    ]
