# Generated by Django 5.2.11 on 2026-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0034_alter_inscripcioncarrera_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='carreras_tutoriadas',
            field=models.ManyToManyField(blank=True, related_name='tutores', to='gestion.plandeestudio', verbose_name='Carreras que Tutorea (Lectura)'),
        ),
    ]
