# Generated by Django 5.2.11 on 2026-09-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0035_docente_carreras_tutoriadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='google_classroom_id',
            field=models.CharField(blank=True, help_text='ID del curso en Google Classroom', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='google_classroom_url',
            field=models.URLField(blank=True, help_text='Link directo al Google Classroom', null=True),
        ),
    ]
