# Generated by Django 5.2.11 on 2026-09-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0036_materia_google_classroom_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Institucional'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico Personal'),
        ),
    ]
