# Generated by Django 5.0.2 on 2026-09-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0037_docente_correo_institucional_alter_docente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGULAR', 'Constancia de Alumno Regular'), ('EXAMEN', 'Certificado de Examen')], max_length=15, verbose_name='Tipo de Trámite')),
                ('fecha_examen', models.DateField(blank=True, null=True, verbose_name='Fecha del Examen')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Autorización'), ('APROBADO', 'Autorizado / Disponible para descarga'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_solicitados', to='gestion.alumno')),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.materia')),
            ],
        ),
    ]
