# Generated by Django 5.2.11 on 2026-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0039_alter_alumno_estado_alumno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No Binario / X')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No Binario / X')], max_length=1, null=True, verbose_name='Género'),
        ),
    ]
