# Generated by Django 5.2.11 on 2026-09-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0040_alter_alumno_sexo_alter_docente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandeestudio',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar para planes históricos que ya no se dictan', verbose_name='Activo'),
        ),
    ]
