# Generated by Django 5.2.11 on 2026-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0041_plandeestudio_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripcion'),
        ),
        migrations.AlterField(
            model_name='inscripcioncarrera',
            name='legajo_numero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de Legajo'),
        ),
    ]
