# Generated by Django 5.2.11 on 2026-09-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0042_alter_inscripcioncarrera_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncarrera',
            name='folio_matriz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio Matriz'),
        ),
        migrations.AddField(
            model_name='inscripcioncarrera',
            name='libro_matriz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Libro Matriz'),
        ),
    ]
