version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sigeet_db
      - POSTGRES_USER=sigeet_user
      - POSTGRES_PASSWORD=supersecret
    restart: always

  web:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 sistema_escolar.wsgi:application"
    volumes:
      - .:/app
    environment:
      - POSTGRES_DB=sigeet_db
      - POSTGRES_USER=sigeet_user
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    restart: always

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
